[target.x86_64-unknown-linux-musl]
linker = "compilers/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc"
[target.aarch64-unknown-linux-musl]
linker = "compilers/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc"
[target.armv7-unknown-linux-musleabihf]
linker = "compilers/armv7l-linux-musleabihf-cross/bin/armv7l-linux-musleabihf-gcc"
[target.arm-unknown-linux-musleabihf]
linker = "compilers/arm-linux-musleabihf-cross/bin/arm-linux-musleabihf-gcc"

[env]
# tell pkg-config where to find the cross compilers
# see: https://github.com/rust-lang/pkg-config-rs#external-configuration-via-target-scoped-environment-variables
CC_x86_64-unknown-linux-musl = { value = "compilers/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc", relative = true }
AR_x86_64-unknown-linux-musl = { value = "compilers/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc-ar", relative = true }

CC_aarch64-unknown-linux-musl = { value = "compilers/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc", relative = true }
AR_aarch64-unknown-linux-musl = { value = "compilers/aarch64-linux-musl-cross/bin/aarch64-linux-musl-ar", relative = true }

CC_armv7-unknown-linux-musleabihf = { value = "compilers/armv7l-linux-musleabihf-cross/bin/armv7l-linux-musleabihf-gcc", relative = true }
AR_armv7-unknown-linux-musleabihf = { value = "compilers/armv7l-linux-musleabihf-cross/bin/armv7l-linux-musleabihf-ar", relative = true }

CC_arm-unknown-linux-musleabihf = { value = "compilers/arm-linux-musleabihf-cross/bin/arm-linux-musleabihf-gcc", relative = true }
AR_arm-unknown-linux-musleabihf = { value = "compilers/arm-linux-musleabihf-cross/bin/arm-linux-musleabihf-ar", relative = true }
