[package]
name = "setup_crosscompile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "rustls"] }
flate2 = "1"
tar = "0.4"
