name: Changelog edited
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main
      - develop
jobs:
  build:
    name: Check Actions
    runs-on: ubuntu-latest
    steps:
      - name: Check if pull request was opened by a bot
        run: |
          if [[ "${{ github.event.pull_request.user.login }}" =~ "bot" ]]; then
            echo "Pull request was opened by a bot, exiting."
            exit 1
          fi
      - uses: actions/checkout@v1
      - name: Changelog check
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: CHANGELOG.md # default `CHANGELOG.adoc`
          checkNotification: Simple # default `Detailed`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

