name: Changelog edited
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main
      - develop
jobs:
  build:
    name: Check Actions
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.user.type != 'Bot'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Changelog check
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: CHANGELOG.md # default `CHANGELOG.adoc`
          checkNotification: Simple # default `Detailed`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

