name: Tests

on:
  pull_request:
    # complemented with branch protection on main this will 
    # need to complete successfully before we auto deploy from main
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: unit and integration tests
      run: cargo test

  test_cross_compilation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo2-${{ hashFiles('**/Cargo.lock') }}

    - name: setup crosscompiler
      working-directory: ./setup_crosscompile
      run: cargo r
    - name: add aarch64 musl toolchain
      run: rustup target add aarch64-unknown-linux-musl
    - name: crosscompile
      working-directory: ./main
      run: cargo b --target aarch64-unknown-linux-musl
      
